aruco_detector:
  ros__parameters:
    dictionary: "DICT_6X6_250"
    target_id: 0
    marker_length_m: 0.50
    publish_debug_image: true
    image_topic: "/fixed_camera/camera/image_raw"
    camera_info_topic: "/fixed_camera/camera/camera_info"
    use_sim_time: true
